In [ ]:
''''Assignment #4
Rezwan-Ul-Alam (ID: 2011659042)
Md. Nur Alam Jowel (ID: 2012355042)
Raian Ruku (ID: 2013409642)'''

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/data/DT-Wage.csv')

In [ ]:
df

# Data Visualization, Preprocessing, Label Encoding

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        3000 non-null   int64
 1   age         3000 non-null   int64
 2   maritl      3000 non-null   object
 3   race        3000 non-null   object
 4   education   3000 non-null   object
 5   region      3000 non-null   object
 6   jobclass    3000 non-null   object
 7   health      3000 non-null   object
 8   health_ins  3000 non-null   object
 9   logwage     3000 non-null   float64
 10  wage        3000 non-null   float64
dtypes: float64(2), int64(2), object(7)
memory usage: 257.9+ KB

In [ ]:
for column in df.columns:
    total = df[column].isnull().sum()
    print(f"Column '{column}' has {total} null values")
    print("\n")

Column 'year' has 0 null values


Column 'age' has 0 null values


Column 'maritl' has 0 null values


Column 'race' has 0 null values


Column 'education' has 0 null values


Column 'region' has 0 null values


Column 'jobclass' has 0 null values


Column 'health' has 0 null values


Column 'health_ins' has 0 null values


Column 'logwage' has 0 null values


Column 'wage' has 0 null values

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_enc=LabelEncoder()
df['maritl'] = label_enc.fit_transform(df['maritl'])
df['race'] = label_enc.fit_transform(df['race'])
df['education'] = label_enc.fit_transform(df['education'])
df['region'] = label_enc.fit_transform(df['region'])
df['jobclass'] = label_enc.fit_transform(df['jobclass'])
df['health'] = label_enc.fit_transform(df['health'])
df['health_ins'] = label_enc.fit_transform(df['health_ins'])

In [ ]:
df

,year,age,maritl,race,education,region,jobclass,health,health_ins,logwage,wage
0,2006,18,0,0,0,0,0,0,1,4.318063,75.043154
1,2004,24,0,0,3,0,1,1,1,4.255273,70.476020
2,2003,45,1,0,2,0,0,0,0,4.875061,130.982177
3,2003,43,1,2,3,0,1,1,0,5.041393,154.685293
4,2005,50,3,0,1,0,1,0,0,4.318063,75.043154
...,...,...,...,...,...,...,...,...,...,...,...
2995,2008,44,1,0,2,0,0,1,0,5.041393,154.685293
2996,2007,30,1,0,1,0,0,1,1,4.602060,99.689464
2997,2005,27,1,1,0,0,0,0,1,4.193125,66.229408
2998,2005,27,0,0,2,0,0,1,0,4.477121,87.981033
2999,2009,55,4,0,1,0,0,0,0,4.505150,90.481913

In [ ]:
df.describe()

,year,age,maritl,race,education,region,jobclass,health,health_ins,logwage,wage
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.0,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,2005.791000,42.414667,0.981333,0.261333,2.010000,0.0,0.485333,0.714000,0.305667,4.653905,111.703608
std,2.026167,11.542406,0.811914,0.627564,1.215618,0.0,0.499868,0.451965,0.460766,0.351753,41.728595
min,2003.000000,18.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,3.000000,20.085537
25%,2004.000000,33.750000,1.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,4.447158,85.383940
50%,2006.000000,42.000000,1.000000,0.000000,2.000000,0.0,0.000000,1.000000,0.000000,4.653213,104.921507
75%,2008.000000,51.000000,1.000000,0.000000,3.000000,0.0,1.000000,1.000000,1.000000,4.857332,128.680488
max,2009.000000,80.000000,4.000000,3.000000,4.000000,0.0,1.000000,1.000000,1.000000,5.763128,318.342430

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        3000 non-null   int64
 1   age         3000 non-null   int64
 2   maritl      3000 non-null   int64
 3   race        3000 non-null   int64
 4   education   3000 non-null   int64
 5   region      3000 non-null   int64
 6   jobclass    3000 non-null   int64
 7   health      3000 non-null   int64
 8   health_ins  3000 non-null   int64
 9   logwage     3000 non-null   float64
 10  wage        3000 non-null   float64
dtypes: float64(2), int64(9)
memory usage: 257.9 KB

In [ ]:
df['year'] = df['year'].astype('float64')
df['age'] = df['age'].astype('float64')
df['maritl'] = df['maritl'].astype('float64')
df['race'] = df['race'].astype('float64')
df['education'] = df['education'].astype('float64')
df['region'] = df['region'].astype('float64')
df['jobclass'] = df['jobclass'].astype('float64')
df['health'] = df['health'].astype('float64')
df['health_ins'] = df['health_ins'].astype('float64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        3000 non-null   float64
 1   age         3000 non-null   float64
 2   maritl      3000 non-null   float64
 3   race        3000 non-null   float64
 4   education   3000 non-null   float64
 5   region      3000 non-null   float64
 6   jobclass    3000 non-null   float64
 7   health      3000 non-null   float64
 8   health_ins  3000 non-null   float64
 9   logwage     3000 non-null   float64
 10  wage        3000 non-null   float64
dtypes: float64(11)
memory usage: 257.9 KB

# Train Test Split

In [ ]:
X = df.iloc[:,:10]
y = df.iloc[:, 10]

print("Shape of x: ", X.shape)
print("Shape of y: ", y.shape)

Shape of x:  (3000, 10)
Shape of y:  (3000,)

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [ ]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_val: ", X_val.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("shape of y_val: ", y_val.shape)
print("shape of y_test: ", y_test.shape)

Shape of X_train:  (2100, 10)
Shape of X_val:  (450, 10)
Shape of X_test:  (450, 10)
Shape of y_train:  (2100,)
shape of y_val:  (450,)
shape of y_test:  (450,)

# MinMax Scaler

In [ ]:

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# `MSE function`

In [ ]:
import numpy as np
def calculate_mse(y_true, y_pred):
      mse = np.mean((y_true - y_pred) ** 2)
      return mse

In [ ]:
'''def calculate_mse(y_true, y_pred):
    total_squared_error = 0.0
    n = len(y_true)
    for i in range(n):
        squared_error = (y_true[i] - y_pred[i]) ** 2
        total_squared_error += squared_error
    mse = total_squared_error / n
    return mse'''

# Hyperparameter tuning using validation set for Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

max_depth_values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 3]
best_mse = 100.0
best_parameters = {}
for max_depth in max_depth_values:
    for min_samples_split in min_samples_split_values:
        for min_samples_leaf in min_samples_leaf_values:
            dt_regressor = DecisionTreeRegressor(max_depth=max_depth,
                                                  min_samples_split=min_samples_split,
                                                  min_samples_leaf=min_samples_leaf)
            dt_regressor.fit(X_train_scaled, y_train)
            y_val_pred = dt_regressor.predict(X_val_scaled)
            mse = calculate_mse(y_val, y_val_pred)
            print("Mean Squared Error on Validation Set:", mse)

            if mse < best_mse:
                best_mse = mse
                best_parameters['max_depth'] = max_depth
                best_parameters['min_samples_split'] = min_samples_split
                best_parameters['min_samples_leaf'] = min_samples_leaf

print("Best Hyperparameters:", best_parameters)
print("Best MSE for validation set:", best_mse)

best_dt_regressor = DecisionTreeRegressor(**best_parameters)
best_dt_regressor.fit(X_train_scaled, y_train)
y_pred = best_dt_regressor.predict(X_test_scaled)
mse = calculate_mse(y_test, y_pred)
print("Mean Squared Error on Test Set:", mse)

# Hyperparameter tuning using validation set for XGBoost

In [ ]:
from xgboost import XGBRegressor
import numpy as np

max_depth_values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
learning_rate_values = [0.01, 0.05, 0.1, 0.2, 0.3]
n_estimators_values = [50, 100, 150, 200]

best_mse = 1000.0
best_parameters = {}

for max_depth in max_depth_values:
    for learning_rate in learning_rate_values:
        for n_estimators in n_estimators_values:
            xgb_regressor = XGBRegressor(max_depth=max_depth,
                                         learning_rate=learning_rate,
                                         n_estimators=n_estimators,
                                         random_state=42)
            xgb_regressor.fit(X_train_scaled, y_train)
            y_val_pred = xgb_regressor.predict(X_val_scaled)
            mse = calculate_mse(y_val, y_val_pred)
            print("Mean Squared Error on Validation Set:", mse)

            if mse < best_mse:
                best_mse = mse
                best_parameters['max_depth'] = max_depth
                best_parameters['learning_rate'] = learning_rate
                best_parameters['n_estimators'] = n_estimators

print("Best Hyperparameters:", best_parameters)
print("Best MSE for validation set:", best_mse)

best_xgb_regressor = XGBRegressor(**best_parameters, random_state=42)
best_xgb_regressor.fit(X_train_scaled, y_train)
y_pred = best_xgb_regressor.predict(X_test_scaled)
mse = calculate_mse(y_val, y_val_pred)
print("Mean Squared Error on Test Set:", mse)

Mean Squared Error on Validation Set: 948.5034713231554
Mean Squared Error on Validation Set: 597.6164461944744
Mean Squared Error on Validation Set: 384.76875663195585
Mean Squared Error on Validation Set: 251.64642428440825
Mean Squared Error on Validation Set: 159.65360075264567
Mean Squared Error on Validation Set: 26.999676109814963
Mean Squared Error on Validation Set: 7.961449197252407
Mean Squared Error on Validation Set: 3.510948919455771
Mean Squared Error on Validation Set: 26.199451477872895
Mean Squared Error on Validation Set: 4.490155410544375
Mean Squared Error on Validation Set: 2.3388703167388396
Mean Squared Error on Validation Set: 1.9095596517789553
Mean Squared Error on Validation Set: 8.367985699446429
Mean Squared Error on Validation Set: 5.9381502075297945
Mean Squared Error on Validation Set: 5.11445977547487
Mean Squared Error on Validation Set: 4.554393285375988
Mean Squared Error on Validation Set: 20.137494301052993
Mean Squared Error on Validation Set: 15.287346445338125
Mean Squared Error on Validation Set: 12.411336197136274
Mean Squared Error on Validation Set: 10.566312099005582
Mean Squared Error on Validation Set: 683.9448322024443
Mean Squared Error on Validation Set: 290.1247882309808
Mean Squared Error on Validation Set: 126.50117917056005
Mean Squared Error on Validation Set: 57.22666484774819
Mean Squared Error on Validation Set: 25.54541300063459
Mean Squared Error on Validation Set: 2.449034841644268
Mean Squared Error on Validation Set: 0.7121363031418076
Mean Squared Error on Validation Set: 0.5056071910798018
Mean Squared Error on Validation Set: 2.4516027844454644
Mean Squared Error on Validation Set: 0.7327090548718128
Mean Squared Error on Validation Set: 0.6528535354201125
Mean Squared Error on Validation Set: 0.5450131818683341
Mean Squared Error on Validation Set: 2.3659606253273817
Mean Squared Error on Validation Set: 1.3113939515468032
Mean Squared Error on Validation Set: 0.8226868439395816
Mean Squared Error on Validation Set: 0.6164219321327937
Mean Squared Error on Validation Set: 2.184289640941295
Mean Squared Error on Validation Set: 1.1760457405047975
Mean Squared Error on Validation Set: 0.7504468593512041
Mean Squared Error on Validation Set: 0.6592639108385752
Mean Squared Error on Validation Set: 624.3344069903392
Mean Squared Error on Validation Set: 241.02777000034928
Mean Squared Error on Validation Set: 94.72599508395622
Mean Squared Error on Validation Set: 38.149841242446236
Mean Squared Error on Validation Set: 14.791464869507383
Mean Squared Error on Validation Set: 0.896924667069662
Mean Squared Error on Validation Set: 0.40466308861054234
Mean Squared Error on Validation Set: 0.3129965114625026
Mean Squared Error on Validation Set: 0.9444885031725988
Mean Squared Error on Validation Set: 0.3561550555913347
Mean Squared Error on Validation Set: 0.31728539197584293
Mean Squared Error on Validation Set: 0.3003155987038643
Mean Squared Error on Validation Set: 0.6924850619889605
Mean Squared Error on Validation Set: 0.4519740660805117
Mean Squared Error on Validation Set: 0.38120457991344503
Mean Squared Error on Validation Set: 0.37241743559667445
Mean Squared Error on Validation Set: 0.615308081946209
Mean Squared Error on Validation Set: 0.43771696756066614
Mean Squared Error on Validation Set: 0.38694784807310373
Mean Squared Error on Validation Set: 0.3635433718345799
Mean Squared Error on Validation Set: 604.7251932018544
Mean Squared Error on Validation Set: 227.72100865285606
Mean Squared Error on Validation Set: 88.20260820017648
Mean Squared Error on Validation Set: 34.90984169302973
Mean Squared Error on Validation Set: 13.32635180679704
Mean Squared Error on Validation Set: 0.7336015666989046
Mean Squared Error on Validation Set: 0.2995669026909838
Mean Squared Error on Validation Set: 0.26331168157012397
Mean Squared Error on Validation Set: 0.6445759955436616
Mean Squared Error on Validation Set: 0.25953458291985254
Mean Squared Error on Validation Set: 0.30260845900836303
Mean Squared Error on Validation Set: 0.33067800296385724
Mean Squared Error on Validation Set: 0.3204925152015562
Mean Squared Error on Validation Set: 0.33357581547301757
Mean Squared Error on Validation Set: 0.3961000459873136
Mean Squared Error on Validation Set: 0.4090860202562213
Mean Squared Error on Validation Set: 0.9574236154017638
Mean Squared Error on Validation Set: 0.9114546286741362
Mean Squared Error on Validation Set: 0.950436712278001
Mean Squared Error on Validation Set: 0.9598174804667055
Mean Squared Error on Validation Set: 604.2507913761875
Mean Squared Error on Validation Set: 226.98656415407405
Mean Squared Error on Validation Set: 87.62550088914666
Mean Squared Error on Validation Set: 34.621634700935104
Mean Squared Error on Validation Set: 12.970003473129452
Mean Squared Error on Validation Set: 1.2119172927166848
Mean Squared Error on Validation Set: 0.9979506801735581
Mean Squared Error on Validation Set: 0.9974411880238904
Mean Squared Error on Validation Set: 1.1290033978533298
Mean Squared Error on Validation Set: 0.9409742982386362
Mean Squared Error on Validation Set: 0.9525730005982938
Mean Squared Error on Validation Set: 0.955078791116372
Mean Squared Error on Validation Set: 1.1812307881628459
Mean Squared Error on Validation Set: 1.188922976209034
Mean Squared Error on Validation Set: 1.2172171469678654
Mean Squared Error on Validation Set: 1.2271638003497933
Mean Squared Error on Validation Set: 1.2392047041733922
Mean Squared Error on Validation Set: 1.2617998561718293
Mean Squared Error on Validation Set: 1.2820277657544876
Mean Squared Error on Validation Set: 1.2696030262757758
Mean Squared Error on Validation Set: 604.1338265539147
Mean Squared Error on Validation Set: 226.92584182479322
Mean Squared Error on Validation Set: 87.68451698808106
Mean Squared Error on Validation Set: 34.618687147055454
Mean Squared Error on Validation Set: 12.981870445610168
Mean Squared Error on Validation Set: 1.3097068027454324
Mean Squared Error on Validation Set: 1.1111565261535208
Mean Squared Error on Validation Set: 1.1253730328940657
Mean Squared Error on Validation Set: 1.3377250792617752
Mean Squared Error on Validation Set: 1.1352397730078698
Mean Squared Error on Validation Set: 1.1166049079799705
Mean Squared Error on Validation Set: 1.1299654837192314
Mean Squared Error on Validation Set: 0.9956248966880559
Mean Squared Error on Validation Set: 1.0365678255841364
Mean Squared Error on Validation Set: 1.0632741928098441
Mean Squared Error on Validation Set: 1.0787710839887688
Mean Squared Error on Validation Set: 1.2366179813900953
Mean Squared Error on Validation Set: 1.31864442517003
Mean Squared Error on Validation Set: 1.333561055186758
Mean Squared Error on Validation Set: 1.3348341906136316
Mean Squared Error on Validation Set: 604.0635509568583
Mean Squared Error on Validation Set: 226.89740812112788
Mean Squared Error on Validation Set: 87.59102824680132
Mean Squared Error on Validation Set: 34.593203593988676
Mean Squared Error on Validation Set: 12.921722047995669
Mean Squared Error on Validation Set: 1.355151074098369
Mean Squared Error on Validation Set: 1.1197927100251346
Mean Squared Error on Validation Set: 1.108456095053142
Mean Squared Error on Validation Set: 1.2407598698492632
Mean Squared Error on Validation Set: 1.0392128522429362
Mean Squared Error on Validation Set: 1.0567268475497453
Mean Squared Error on Validation Set: 1.0643819630701248
Mean Squared Error on Validation Set: 1.0077801281318934
Mean Squared Error on Validation Set: 0.9877549523514242
Mean Squared Error on Validation Set: 0.9998005415224915
Mean Squared Error on Validation Set: 1.0106145123914345
Mean Squared Error on Validation Set: 1.244296260484068
Mean Squared Error on Validation Set: 1.257512536020797
Mean Squared Error on Validation Set: 1.2619237369820817
Mean Squared Error on Validation Set: 1.2629932081143802
Mean Squared Error on Validation Set: 604.1693146551802
Mean Squared Error on Validation Set: 226.92435470768146
Mean Squared Error on Validation Set: 87.63774294623855
Mean Squared Error on Validation Set: 34.630900332204575
Mean Squared Error on Validation Set: 12.922232722015739
Mean Squared Error on Validation Set: 1.3869925699567642
Mean Squared Error on Validation Set: 1.1680472419604717
Mean Squared Error on Validation Set: 1.1678424166298649
Mean Squared Error on Validation Set: 1.1685188357650105
Mean Squared Error on Validation Set: 0.9854792354765356
Mean Squared Error on Validation Set: 0.9932684688167016
Mean Squared Error on Validation Set: 0.992377767271317
Mean Squared Error on Validation Set: 1.0881712506823928
Mean Squared Error on Validation Set: 1.0474725843232855
Mean Squared Error on Validation Set: 1.0521769305462396
Mean Squared Error on Validation Set: 1.055724776121609
Mean Squared Error on Validation Set: 1.2232392877878204
Mean Squared Error on Validation Set: 1.2246769673519187
Mean Squared Error on Validation Set: 1.2244969203933262
Mean Squared Error on Validation Set: 1.225145728459566
Mean Squared Error on Validation Set: 604.1693265306926
Mean Squared Error on Validation Set: 226.9245210217064
Mean Squared Error on Validation Set: 87.6380051186891
Mean Squared Error on Validation Set: 34.631025261443966
Mean Squared Error on Validation Set: 12.922661683216019
Mean Squared Error on Validation Set: 1.3120668813812137
Mean Squared Error on Validation Set: 1.085987662533559
Mean Squared Error on Validation Set: 1.0818077947024163
Mean Squared Error on Validation Set: 1.1744809719496574
Mean Squared Error on Validation Set: 1.0226468876520372
Mean Squared Error on Validation Set: 1.0319603393390004
Mean Squared Error on Validation Set: 1.034426817722949
Mean Squared Error on Validation Set: 1.0801669989290934
Mean Squared Error on Validation Set: 1.033294820318286
Mean Squared Error on Validation Set: 1.0345912814413305
Mean Squared Error on Validation Set: 1.0357961786197956
Mean Squared Error on Validation Set: 1.2593187446697105
Mean Squared Error on Validation Set: 1.2637724914207615
Mean Squared Error on Validation Set: 1.2638552946339858
Mean Squared Error on Validation Set: 1.263966732691435
Mean Squared Error on Validation Set: 604.1693300381901
Mean Squared Error on Validation Set: 226.92452656157857
Mean Squared Error on Validation Set: 87.715546315542
Mean Squared Error on Validation Set: 34.662918268304864
Mean Squared Error on Validation Set: 12.922757793908037
Mean Squared Error on Validation Set: 1.3205821908833362
Mean Squared Error on Validation Set: 1.0871171059811298
Mean Squared Error on Validation Set: 1.0573549324661644
Mean Squared Error on Validation Set: 1.1932605086339474
Mean Squared Error on Validation Set: 1.0329344807689467
Mean Squared Error on Validation Set: 1.0357725134965086
Mean Squared Error on Validation Set: 1.0353755604289998
Mean Squared Error on Validation Set: 1.0690123953884247
Mean Squared Error on Validation Set: 1.0171607330191963
Mean Squared Error on Validation Set: 1.019581185999986
Mean Squared Error on Validation Set: 1.0194758741200387
Mean Squared Error on Validation Set: 1.2946888438490647
Mean Squared Error on Validation Set: 1.2961174210961577
Mean Squared Error on Validation Set: 1.29627185965044
Mean Squared Error on Validation Set: 1.29627185965044
Best Hyperparameters: {'max_depth': 4, 'learning_rate': 0.1, 'n_estimators': 100}
Best MSE for validation set: 0.25953458291985254
Mean Squared Error on Test Set: 1.29627185965044

In [40]:
file_path = '/content/gdrive/MyDrive/data/processed_dataset_DT_wage.xlsx'
df.to_excel(file_path, index=False)